name: Main Pipeline

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 21

jobs:
  build-and-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'zulu'
          cache: 'gradle'

      - name: Run tests
        timeout-minutes: 30
        run: ./gradlew test
